# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Nicole Hall
description: "I'm Nicole. I am a software developer, SDET, and Solution Engineer. I am taking my career to the next level as a data scientist to drive data-driven innovations that will shape the future."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Denver, CO"
resume_url: /docs/Nicole_Hall_SE_Oct_2024.pdf
avatar_image: /img/yellow sweater square.png

#-------------------------------
# Contact links
linkedin: "https://www.linkedin.com/in/nicolealexandrahall/" # Add your LinkedIn handle

github: "https://github.com/NicoleHall"  # Add your GitHub handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false

#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
